[package]
name = "roli"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.13"

[dev-dependencies]
clap = { version = "4.0.26", features = ["derive"] }